# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
    - oldrel
    - release
    - devel

matrix:
    include:
        - os: linux
        - os: osx
          fortran: false

after_success:
    - Rscript -e 'covr::codecov()'

