# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acceptanceTheta <- function(responses, cv, alphas, deltas, taus, SD) {
    .Call('ggumR_acceptanceTheta', PACKAGE = 'ggumR', responses, cv, alphas, deltas, taus, SD)
}

acceptanceAlpha <- function(responses, thetas, cv, delta, taus, SD) {
    .Call('ggumR_acceptanceAlpha', PACKAGE = 'ggumR', responses, thetas, cv, delta, taus, SD)
}

acceptanceDelta <- function(responses, thetas, alpha, cv, taus, SD) {
    .Call('ggumR_acceptanceDelta', PACKAGE = 'ggumR', responses, thetas, alpha, cv, taus, SD)
}

acceptanceTau <- function(k, responses, thetas, alpha, delta, taus, SD) {
    .Call('ggumR_acceptanceTau', PACKAGE = 'ggumR', k, responses, thetas, alpha, delta, taus, SD)
}

#' The Four Parameter Beta Distribution
#'
#' Provides probability density, cumulative distribution, quantile, and random
#' number generating functions for the four parameter beta distribution.
#'
#' @param x,q A numeric vector of quantiles
#' @param p A numeric vector of probabilities
#' @param n The number of observations to generate
#' @param shape1 Shape 1
#' @param shape2 Shape 2
#' @param a The lowest possible value of the distribution
#' @param b The highest possible value of the distribution
#'
#' @return \code{d4beta} gives gives the density, \code{p4beta} gives the
#'   distribution function, \code{q4beta} gives the quantile function, and
#'   \code{r4beta} generates random numbers from the distribution.
#'
#' @name Four Parameter Beta
#' @rdname fourParamBeta
NULL

#' @rdname fourParamBeta
#' @export
d4beta <- function(x, shape1, shape2, a, b) {
    .Call('ggumR_d4beta', PACKAGE = 'ggumR', x, shape1, shape2, a, b)
}

#' @rdname fourParamBeta
#' @export
p4beta <- function(q, shape1, shape2, a, b) {
    .Call('ggumR_p4beta', PACKAGE = 'ggumR', q, shape1, shape2, a, b)
}

#' @rdname fourParamBeta
#' @export
q4beta <- function(p, shape1, shape2, a, b) {
    .Call('ggumR_q4beta', PACKAGE = 'ggumR', p, shape1, shape2, a, b)
}

#' @rdname fourParamBeta
#' @export
r4beta <- function(n, shape1, shape2, a, b) {
    .Call('ggumR_r4beta', PACKAGE = 'ggumR', n, shape1, shape2, a, b)
}

d_4beta <- function(x, shape1, shape2, a, b) {
    .Call('ggumR_d_4beta', PACKAGE = 'ggumR', x, shape1, shape2, a, b)
}

r_4beta <- function(shape1, shape2, a, b) {
    .Call('ggumR_r_4beta', PACKAGE = 'ggumR', shape1, shape2, a, b)
}

#' GGUM MCMC Sampler
#'
#' MCMC sampler for the generalized graded unfolding model (GGUM), utilizing
#' a Metropolis-Hastings algorithm
#'
#' @param responseMatrix A numeric matrix giving the response by each
#'   respondent to each item
#' @param Kvector A numeric vector of length m (the number of items), each
#'   element j of which gives the number of options (K) for item j
#' @param iterations A numeric vector of length one; the number of iterations
#'
#' @return A chain matrix; a numeric matrix with \code{iterations} rows and
#'   one column for every parameter of the model, so that each element of the
#'   matrix gives the value of a parameter for a particular iteration of the
#'   algorithm
#' @export
ggumMCMC <- function(responseMatrix, Kvector, iterations) {
    .Call('ggumR_ggumMCMC', PACKAGE = 'ggumR', responseMatrix, Kvector, iterations)
}

#' GGUM Probability Function
#'
#' Calculate the probability of a response according to the GGUM
#' 
#' The General Graded Unfolding Model (GGUM) is an item response model
#' designed to consider the possibility of disagreement for opposite reasons.
#' This function gives the probability of a respondent's response to a test
#' item given item and respondent parameters. The user can calculate the
#' probability of one particular response or for any number of the possible
#' responses to the item (see the \code{k} parameter described below).
#' 
#' @param k A numeric vector giving the item(s) for which response
#'   probability should be calculated
#' @param theta A numeric vector of length one giving the respondent's latent
#'   trait score
#' @param alpha A numeric vector of length one giving the item's
#'   discrimination parameter
#' @param delta A numeric vector of length one giving the item's location
#'   parameter
#' @param tau A numeric vector of length K (the number of possible responses)
#'   giving the options' threshold parameters; the first element of \code{tau}
#'   should be zero
#'
#' @return A numeric vector the same length of \code{k} giving the response
#'   probabilities
#' @rdname ggumProbability
#' @export
ggumProbability <- function(k, theta, alpha, delta, tau) {
    .Call('ggumR_ggumProbability', PACKAGE = 'ggumR', k, theta, alpha, delta, tau)
}

#' The location-scale T distribution.
#'
#' Density, distribution function, quantile function, and random number
#' generation for the T distribution shifted by location parameter 'mu' and
#' scaled by 'sigma'.
#'
#' @param n A numeric vector of length one; the number of numbers to generate
#' @param x,q A numeric vector of the quantiles of interest
#' @param p A numeric vector of the probabilities of interest
#' @param df A numeric vector of length one; the degrees of freedom of the
#'   distribution
#' @param sigma A numeric vector of length one; the scale parameter
#' @param mu A numeric vector of length one; the shifting parameter
#'
#' @return 'dlst' gives the density, 'plst' gives the distribution function,
#'     'qlst' gives the quantile function, and 'rlst' generates random numbers
#'     from the distribution
#'     
#' @references Jackman, Simon. 2009. \emph{Bayesian Analysis for the Social
#'     Sciences}. Wiley. p. 507.
#'
#' @name Location-Scale T
#' @rdname scaledT-dist
NULL

#' @rdname scaledT-dist
#' @export
dlst <- function(x, df, mu, sigma) {
    .Call('ggumR_dlst', PACKAGE = 'ggumR', x, df, mu, sigma)
}

#' @rdname scaledT-dist
#' @export
plst <- function(q, df, mu, sigma) {
    .Call('ggumR_plst', PACKAGE = 'ggumR', q, df, mu, sigma)
}

#' @rdname scaledT-dist
#' @export
qlst <- function(p, df, mu, sigma) {
    .Call('ggumR_qlst', PACKAGE = 'ggumR', p, df, mu, sigma)
}

#' @rdname scaledT-dist
#' @export
rlst <- function(n, df, mu, sigma) {
    .Call('ggumR_rlst', PACKAGE = 'ggumR', n, df, mu, sigma)
}

d_lst <- function(x, df, mu, sigma) {
    .Call('ggumR_d_lst', PACKAGE = 'ggumR', x, df, mu, sigma)
}

p_lst <- function(q, df, mu, sigma) {
    .Call('ggumR_p_lst', PACKAGE = 'ggumR', q, df, mu, sigma)
}

#' The Truncated Location-Scale T distribution.
#'
#' Provides probability density, cumulative distribution, quantile, and random
#' number generating functions for the truncated location-scale T distribution.
#'
#' @param x,q A numeric vector of quantiles
#' @param p A numeric vector of probabilities
#' @param n The number of observations to generate
#' @param df A numeric vector of length one; the degrees of freedom of the
#'   distribution
#' @param mu A numeric vector of length one; the shifting parameter
#' @param sigma A numeric vector of length one; the scale parameter
#' @param a The lowest possible value of the distribution
#' @param b The highest possible value of the distribution
#'
#' @return \code{dtrunclst} gives gives the density, \code{ptrunclst} gives
#'   the distribution function, \code{qtrunclst} gives the quantile function,
#'   and \code{rtrunclst} generates random numbers from the distribution.
#'
#' @name Truncated Location-Scale T
#' @rdname trunclst
NULL

#' @rdname trunclst
#' @export
dtrunclst <- function(x, df, mu, sigma, a, b) {
    .Call('ggumR_dtrunclst', PACKAGE = 'ggumR', x, df, mu, sigma, a, b)
}

#' @rdname trunclst
#' @export
ptrunclst <- function(q, df, mu, sigma, a, b) {
    .Call('ggumR_ptrunclst', PACKAGE = 'ggumR', q, df, mu, sigma, a, b)
}

#' @rdname trunclst
#' @export
qtrunclst <- function(p, df, mu, sigma, a, b) {
    .Call('ggumR_qtrunclst', PACKAGE = 'ggumR', p, df, mu, sigma, a, b)
}

#' @rdname trunclst
#' @export
rtrunclst <- function(n, df, mu, sigma, a, b) {
    .Call('ggumR_rtrunclst', PACKAGE = 'ggumR', n, df, mu, sigma, a, b)
}

r_trunclst <- function(df, mu, sigma, a, b) {
    .Call('ggumR_r_trunclst', PACKAGE = 'ggumR', df, mu, sigma, a, b)
}

#' The Truncated Normal Distribution
#'
#' Provides probability density, cumulative distribution, quantile, and random
#' number generating functions for the truncated normal distribution.
#'
#' @param x,q A numeric vector of quantiles
#' @param p A numeric vector of probabilities
#' @param n The number of observations to generate
#' @param mean The mean of the distribution
#' @param SD The standard deviation of the distribution
#' @param a The lowest possible value of the distribution
#' @param b The highest possible value of the distribution
#'
#' @return \code{dtruncnorm} gives gives the density, \code{ptruncnorm} gives
#'   the distribution function, \code{qtruncnorm} gives the quantile function,
#'   and \code{rtruncnorm} generates random numbers from the distribution.
#'
#' @name Truncated Normal
#' @rdname truncnorm
NULL

#' @rdname truncnorm
#' @export
dtruncnorm <- function(x, mean, SD, a, b) {
    .Call('ggumR_dtruncnorm', PACKAGE = 'ggumR', x, mean, SD, a, b)
}

#' @rdname truncnorm
#' @export
ptruncnorm <- function(q, mean, SD, a, b) {
    .Call('ggumR_ptruncnorm', PACKAGE = 'ggumR', q, mean, SD, a, b)
}

#' @rdname truncnorm
#' @export
qtruncnorm <- function(p, mean, SD, a, b) {
    .Call('ggumR_qtruncnorm', PACKAGE = 'ggumR', p, mean, SD, a, b)
}

#' @rdname truncnorm
#' @export
rtruncnorm <- function(n, mean, SD, a, b) {
    .Call('ggumR_rtruncnorm', PACKAGE = 'ggumR', n, mean, SD, a, b)
}

r_truncnorm <- function(mean, SD, a, b) {
    .Call('ggumR_r_truncnorm', PACKAGE = 'ggumR', mean, SD, a, b)
}

