# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_thetas <- function(n, mean, sd) {
    .Call('_ggum_init_thetas', PACKAGE = 'ggum', n, mean, sd)
}

init_alphas <- function(m, shape1, shape2, a, b) {
    .Call('_ggum_init_alphas', PACKAGE = 'ggum', m, shape1, shape2, a, b)
}

init_deltas <- function(m, shape1, shape2, a, b) {
    .Call('_ggum_init_deltas', PACKAGE = 'ggum', m, shape1, shape2, a, b)
}

init_taus <- function(m, shape1, shape2, a, b, K) {
    .Call('_ggum_init_taus', PACKAGE = 'ggum', m, shape1, shape2, a, b, K)
}

.ggumMC3 <- function(data, iters, N, W, temps, thetas, alphas, deltas, taus, K, n, m) {
    .Call('_ggum_ggumMC3', PACKAGE = 'ggum', data, iters, N, W, temps, thetas, alphas, deltas, taus, K, n, m)
}

.ggumMCMC <- function(responseMatrix, iterations, burn_iterations, thetas, alphas, deltas, taus, K, n, m) {
    .Call('_ggum_ggumMCMC', PACKAGE = 'ggum', responseMatrix, iterations, burn_iterations, thetas, alphas, deltas, taus, K, n, m)
}

#' GGUM Probability Function
#'
#' Calculate the probability of a response according to the GGUM
#' 
#' The General Graded Unfolding Model (GGUM) is an item response model
#' designed to consider the possibility of disagreement for opposite reasons.
#' This function gives the probability of a respondent's response to a test
#' item given item and respondent parameters. The user can calculate the
#' probability of one particular response or for any number of the possible
#' responses to the item (see the \code{k} parameter described below).
#'
#' The probability that respondent \eqn{i} chooses option \eqn{k} for item
#' \eqn{j} is given by
#' \deqn{\frac{\exp (\alpha_j [k (\theta_i - \delta_j) -
#' \sum_{m=0}^k \tau_{jm}]) + \exp (\alpha_j [(2K - k - 1)
#' (\theta_i - \delta_j) - \sum_{m=0}^k \tau_{jm}])}{%
#' \sum_{l=0}^{K-1} [\exp (\alpha_j [l (\theta_i - \delta_j) -
#' \sum_{m=0}^l \tau_{jm}]) + \exp (\alpha_j [(2K - l - 1)
#' (\theta_i - \delta_j) - \sum_{m=0}^l \tau_{jm}])]}}{%
#' (exp(\alpha_j [k(\theta_i-\delta_j) - 
#' \Sigma_{m=0}^k \tau_{jm}]) + exp(\alpha_j [(2K - k - 1)
#' (\theta_i - \delta_j) - \Sigma_{m=0}^k \tau_{jm}])) /
#' (\Sigma_{l=0}^{K-1} [exp (\alpha_j [l (\theta_i - \delta_j) -
#' \Sigma_{m=0}^l \tau_{jm}]) + exp (\alpha_j [(2K - l - 1)
#' (\theta_i - \delta_j) - \Sigma_{m=0}^l \tau_{jm}])])},
#' where \eqn{\theta_i} is \eqn{i}'s latent trait parameter,
#' \eqn{\alpha_j} is the item's discrimination paramter,
#' \eqn{\delta_j} is the item's location paramter,
#' \eqn{\tau_{j0}, \ldots, \tau_{j(K-1)}} are the options' threshold
#' parameters, and \eqn{\tau_{j0}} is 0,
#' \eqn{K} is the number of options for item \eqn{j}, and
#' the options are indexed by \eqn{k = 0, \ldots, K-1}.
#' 
#' @param k A numeric vector giving the item(s) for which response
#'   probability should be calculated
#' @param theta A numeric vector of length one giving the respondent's latent
#'   trait score
#' @param alpha A numeric vector of length one giving the item's
#'   discrimination parameter
#' @param delta A numeric vector of length one giving the item's location
#'   parameter
#' @param tau A numeric vector of length K (the number of possible responses)
#'   giving the options' threshold parameters; the first element of \code{tau}
#'   should be zero
#'
#' @return A numeric vector the same length of \code{k} giving the response
#'   probabilities
#'
#' @references Roberts, James S., John R. Donoghue, and James E. Laughlin.
#'   2000. ``A General Item Response Theory Model for Unfolding
#'   Unidimensional Polytomous Responses." \emph{Applied Psychological
#'   Measurement} 24(1): 3--32.
#' @references de la Torre, Jimmy, Stephen Stark, and Oleksandr S.
#'   Chernyshenko. 2006. ``Markov Chain Monte Carlo Estimation of Item
#'   Parameters for the Generalized Graded Unfolding Model." \emph{Applied
#'   Psychological Measurement} 30(3): 216--232.
#'
#' @rdname ggumProbability
#' @export
ggumProbability <- function(k, theta, alpha, delta, tau) {
    .Call('_ggum_ggumProbability', PACKAGE = 'ggum', k, theta, alpha, delta, tau)
}

prob <- function(choice, th, a, d, t) {
    .Call('_ggum_prob', PACKAGE = 'ggum', choice, th, a, d, t)
}

probCol <- function(choices, thetas, a, d, t) {
    .Call('_ggum_probCol', PACKAGE = 'ggum', choices, thetas, a, d, t)
}

probRow <- function(choices, th, a, d, t) {
    .Call('_ggum_probRow', PACKAGE = 'ggum', choices, th, a, d, t)
}

log_prob <- function(choice, th, a, d, t) {
    .Call('_ggum_log_prob', PACKAGE = 'ggum', choice, th, a, d, t)
}

log_probCol <- function(choices, thetas, a, d, t) {
    .Call('_ggum_log_probCol', PACKAGE = 'ggum', choices, thetas, a, d, t)
}

log_probRow <- function(choices, th, a, d, t) {
    .Call('_ggum_log_probRow', PACKAGE = 'ggum', choices, th, a, d, t)
}

tune_proposals <- function(responseMatrix, thetas, alphas, deltas, taus, K, burn_iters, n, m) {
    .Call('_ggum_tune_proposals', PACKAGE = 'ggum', responseMatrix, thetas, alphas, deltas, taus, K, burn_iters, n, m)
}

update_alpha_MCMC <- function(responses, thetas, cv, delta, taus, SD) {
    .Call('_ggum_update_alpha_MCMC', PACKAGE = 'ggum', responses, thetas, cv, delta, taus, SD)
}

update_delta_MCMC <- function(responses, thetas, alpha, cv, taus, SD) {
    .Call('_ggum_update_delta_MCMC', PACKAGE = 'ggum', responses, thetas, alpha, cv, taus, SD)
}

update_tau_MCMC <- function(k, responses, thetas, alpha, delta, taus, SD) {
    .Call('_ggum_update_tau_MCMC', PACKAGE = 'ggum', k, responses, thetas, alpha, delta, taus, SD)
}

update_theta_MC3 <- function(cv, choices, a, d, t, temp, SD) {
    .Call('_ggum_update_theta_MC3', PACKAGE = 'ggum', cv, choices, a, d, t, temp, SD)
}

update_alpha_MC3 <- function(cv, choices, th, d, t, temp, SD) {
    .Call('_ggum_update_alpha_MC3', PACKAGE = 'ggum', cv, choices, th, d, t, temp, SD)
}

update_delta_MC3 <- function(cv, choices, th, a, t, temp, SD) {
    .Call('_ggum_update_delta_MC3', PACKAGE = 'ggum', cv, choices, th, a, t, temp, SD)
}

update_tau_MC3 <- function(k, choices, th, a, d, t, temp, SD) {
    .Call('_ggum_update_tau_MC3', PACKAGE = 'ggum', k, choices, th, a, d, t, temp, SD)
}

