# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The Four Parameter Beta Distribution
#'
#' Provides probability density, cumulative distribution, quantile, and random
#' number generating functions for the four parameter beta distribution.
#'
#' @param x,q A numeric vector of quantiles
#' @param p A numeric vector of probabilities
#' @param n The number of observations to generate
#' @param shape1 Shape 1
#' @param shape2 Shape 2
#' @param a The lowest possible value of the distribution
#' @param b The highest possible value of the distribution
#'
#' @return \code{d4beta} gives gives the density, \code{p4beta} gives the
#'   distribution function, \code{q4beta} gives the quantile function, and
#'   \code{r4beta} generates random numbers from the distribution.
#'
#' @name Four Parameter Beta
#' @rdname fourParamBeta
NULL

#' @rdname fourParamBeta
#' @export
d4beta <- function(x, shape1, shape2, a, b) {
    .Call('_ggum_d4beta', PACKAGE = 'ggum', x, shape1, shape2, a, b)
}

#' @rdname fourParamBeta
#' @export
p4beta <- function(q, shape1, shape2, a, b) {
    .Call('_ggum_p4beta', PACKAGE = 'ggum', q, shape1, shape2, a, b)
}

#' @rdname fourParamBeta
#' @export
q4beta <- function(p, shape1, shape2, a, b) {
    .Call('_ggum_q4beta', PACKAGE = 'ggum', p, shape1, shape2, a, b)
}

#' @rdname fourParamBeta
#' @export
r4beta <- function(n, shape1, shape2, a, b) {
    .Call('_ggum_r4beta', PACKAGE = 'ggum', n, shape1, shape2, a, b)
}

d_4beta <- function(x, shape1, shape2, a, b) {
    .Call('_ggum_d_4beta', PACKAGE = 'ggum', x, shape1, shape2, a, b)
}

r_4beta <- function(shape1, shape2, a, b) {
    .Call('_ggum_r_4beta', PACKAGE = 'ggum', shape1, shape2, a, b)
}

#' GGUM MC3
#'
#' Metropolis Coupled Markov Chain Monte Carlo Sampling for the GGUM
#'
#' @param data A numeric matrix giving the individuals' responses
#' @param iters A vector of length one giving the number of iterations
#' @param N The number of chains
#' @param W The period by which to attempt chain swaps; e.g. if W = 100,
#'   a state swap will be proposed between two randomly selected chains
#'   every 100 iterations
#' @param Temps An optional provision of the temperatures for the chains;
#'   if not provided, each temperature T_t for t < N is given by
#'   T_{t+1} * (t + 1), and T_N = 1.
#'
#' @return A numeric matrix giving the parameter values at each iteration
#'   for the cold chain
#'
#' @seealso \code{\link{ggumProbability}}, \code{\link{ggumMC3}}
#'
#' @export
ggumMC3 <- function(data, iters, N, W, Temps = NULL) {
    .Call('_ggum_ggumMC3', PACKAGE = 'ggum', data, iters, N, W, Temps)
}

#' GGUM MCMC Sampler
#'
#' MCMC sampler for the generalized graded unfolding model (GGUM), utilizing
#' a Metropolis-Hastings algorithm
#'
#' \code{ggumMCMC} provides \code{R} implementation of an MCMC sampler for
#' the GGUM, based heavily on the algorithm given in de la Torre et al (2006);
#' though the package allows parameter estimation from \code{R},
#' the functions are actually written in \code{C++} to allow for reasonable
#' execution time.
#' Our sampler creates random ititial values for the parameters of the model,
#' according to their prior distributions.
#' Then, for the first 5000 iterations, the sampler, one parameter at a time,
#' will make a proposal from a normal distribution with a mean of the current
#' parameter value and a standard deviation of one, and accept the proposal
#' probabilistically using a standard Metropolis-Hastings acceptance ratio.
#' For the remainder of the iterations, the same process is followed
#' but the \eqn{\sigma} parameter for the proposal density is the standard
#' deviation of the previous 5000 values of the parameter.
#' A matrix is returned giving the value of every parameter at
#' every iteration.
#'
#' @section Warning:
#' Typically, up to 5000 iterations are needed for convergence,
#' and specifying less than 5000 iterations will cause an error.
#' Also, theta and delta parameters often have multi-modal posterior
#' distributions, and in some cases chains may converge to the wrong
#' mode for both parameters; in other words, the questions with the most
#' negative delta parameters will be estimated as having the most positive
#' delta parameters and vice versa, but only if the same happens with
#' the theta parameters. Future package updates will provide a way to
#' specify the expected sign of at least one theta and delta parameter
#' to prevent this occurrence.
#'
#' @param responseMatrix A numeric matrix giving the response by each
#'   respondent to each item
#' @param iterations A numeric vector of length one; the number of iterations
#'   (NOTE: \code{iterations} should be at least 10000, and preferably around
#'   25000, though only values of 5000 or less will cause an error)
#' @param burn_iterations A numeric vector of length one; the number of
#'   "burn-in" iterations to run, during which parameter draws are not
#'   stored
#'
#' @return A chain matrix; a numeric matrix with \code{iterations} rows and
#'   one column for every parameter of the model, so that each element of the
#'   matrix gives the value of a parameter for a particular iteration of the
#'   MCMC algorithm.
#'
#' @seealso \code{\link{ggumProbability}}, \code{\link{ggumMC3}}
#'
#' @references Roberts, James S., John R. Donoghue, and James E. Laughlin.
#'   2000. ``A General Item Response Theory Model for Unfolding
#'   Unidimensional Polytomous Responses." \emph{Applied Psychological
#'   Measurement} 24(1): 3--32.
#' @references de la Torre, Jimmy, Stephen Stark, and Oleksandr S.
#'   Chernyshenko. 2006. ``Markov Chain Monte Carlo Estimation of Item
#'   Parameters for the Generalized Graded Unfolding Model." \emph{Applied
#'   Psychological Measurement} 30(3): 216--232.
#'   algorithm
#' @export
ggumMCMC <- function(responseMatrix, iterations, burn_iterations) {
    .Call('_ggum_ggumMCMC', PACKAGE = 'ggum', responseMatrix, iterations, burn_iterations)
}

#' GGUM Probability Function
#'
#' Calculate the probability of a response according to the GGUM
#' 
#' The General Graded Unfolding Model (GGUM) is an item response model
#' designed to consider the possibility of disagreement for opposite reasons.
#' This function gives the probability of a respondent's response to a test
#' item given item and respondent parameters. The user can calculate the
#' probability of one particular response or for any number of the possible
#' responses to the item (see the \code{k} parameter described below).
#'
#' The probability that respondent \eqn{i} chooses option \eqn{k} for item
#' \eqn{j} is given by
#' \deqn{\frac{\exp (\alpha_j [k (\theta_i - \delta_j) -
#' \sum_{m=0}^k \tau_{jm}]) + \exp (\alpha_j [(2K - k - 1)
#' (\theta_i - \delta_j) - \sum_{m=0}^k \tau_{jm}])}{%
#' \sum_{l=0}^{K-1} [\exp (\alpha_j [l (\theta_i - \delta_j) -
#' \sum_{m=0}^l \tau_{jm}]) + \exp (\alpha_j [(2K - l - 1)
#' (\theta_i - \delta_j) - \sum_{m=0}^l \tau_{jm}])]}}{%
#' (exp(\alpha_j [k(\theta_i-\delta_j) - 
#' \Sigma_{m=0}^k \tau_{jm}]) + exp(\alpha_j [(2K - k - 1)
#' (\theta_i - \delta_j) - \Sigma_{m=0}^k \tau_{jm}])) /
#' (\Sigma_{l=0}^{K-1} [exp (\alpha_j [l (\theta_i - \delta_j) -
#' \Sigma_{m=0}^l \tau_{jm}]) + exp (\alpha_j [(2K - l - 1)
#' (\theta_i - \delta_j) - \Sigma_{m=0}^l \tau_{jm}])])},
#' where \eqn{\theta_i} is \eqn{i}'s latent trait parameter,
#' \eqn{\alpha_j} is the item's discrimination paramter,
#' \eqn{\delta_j} is the item's location paramter,
#' \eqn{\tau_{j0}, \ldots, \tau_{j(K-1)}} are the options' threshold
#' parameters, and \eqn{\tau_{j0}} is 0,
#' \eqn{K} is the number of options for item \eqn{j}, and
#' the options are indexed by \eqn{k = 0, \ldots, K-1}.
#' 
#' @param k A numeric vector giving the item(s) for which response
#'   probability should be calculated
#' @param theta A numeric vector of length one giving the respondent's latent
#'   trait score
#' @param alpha A numeric vector of length one giving the item's
#'   discrimination parameter
#' @param delta A numeric vector of length one giving the item's location
#'   parameter
#' @param tau A numeric vector of length K (the number of possible responses)
#'   giving the options' threshold parameters; the first element of \code{tau}
#'   should be zero
#'
#' @return A numeric vector the same length of \code{k} giving the response
#'   probabilities
#'
#' @references Roberts, James S., John R. Donoghue, and James E. Laughlin.
#'   2000. ``A General Item Response Theory Model for Unfolding
#'   Unidimensional Polytomous Responses." \emph{Applied Psychological
#'   Measurement} 24(1): 3--32.
#' @references de la Torre, Jimmy, Stephen Stark, and Oleksandr S.
#'   Chernyshenko. 2006. ``Markov Chain Monte Carlo Estimation of Item
#'   Parameters for the Generalized Graded Unfolding Model." \emph{Applied
#'   Psychological Measurement} 30(3): 216--232.
#'
#' @rdname ggumProbability
#' @export
ggumProbability <- function(k, theta, alpha, delta, tau) {
    .Call('_ggum_ggumProbability', PACKAGE = 'ggum', k, theta, alpha, delta, tau)
}

prob <- function(choice, th, a, d, t) {
    .Call('_ggum_prob', PACKAGE = 'ggum', choice, th, a, d, t)
}

probCol <- function(choices, thetas, a, d, t) {
    .Call('_ggum_probCol', PACKAGE = 'ggum', choices, thetas, a, d, t)
}

probRow <- function(choices, th, a, d, t) {
    .Call('_ggum_probRow', PACKAGE = 'ggum', choices, th, a, d, t)
}

log_prob <- function(choice, th, a, d, t) {
    .Call('_ggum_log_prob', PACKAGE = 'ggum', choice, th, a, d, t)
}

log_probCol <- function(choices, thetas, a, d, t) {
    .Call('_ggum_log_probCol', PACKAGE = 'ggum', choices, thetas, a, d, t)
}

log_probRow <- function(choices, th, a, d, t) {
    .Call('_ggum_log_probRow', PACKAGE = 'ggum', choices, th, a, d, t)
}

tune_proposals <- function(responseMatrix, thetas, alphas, deltas, taus, K, burn_iters, n, m) {
    .Call('_ggum_tune_proposals', PACKAGE = 'ggum', responseMatrix, thetas, alphas, deltas, taus, K, burn_iters, n, m)
}

update_alpha_MCMC <- function(responses, thetas, cv, delta, taus, SD) {
    .Call('_ggum_update_alpha_MCMC', PACKAGE = 'ggum', responses, thetas, cv, delta, taus, SD)
}

update_delta_MCMC <- function(responses, thetas, alpha, cv, taus, SD) {
    .Call('_ggum_update_delta_MCMC', PACKAGE = 'ggum', responses, thetas, alpha, cv, taus, SD)
}

update_tau_MCMC <- function(k, responses, thetas, alpha, delta, taus, SD) {
    .Call('_ggum_update_tau_MCMC', PACKAGE = 'ggum', k, responses, thetas, alpha, delta, taus, SD)
}

update_theta_MC3 <- function(cv, choices, a, d, t, temp, SD) {
    .Call('_ggum_update_theta_MC3', PACKAGE = 'ggum', cv, choices, a, d, t, temp, SD)
}

update_alpha_MC3 <- function(cv, choices, th, d, t, temp, SD) {
    .Call('_ggum_update_alpha_MC3', PACKAGE = 'ggum', cv, choices, th, d, t, temp, SD)
}

update_delta_MC3 <- function(cv, choices, th, a, t, temp, SD) {
    .Call('_ggum_update_delta_MC3', PACKAGE = 'ggum', cv, choices, th, a, t, temp, SD)
}

update_tau_MC3 <- function(k, choices, th, a, d, t, temp, SD) {
    .Call('_ggum_update_tau_MC3', PACKAGE = 'ggum', k, choices, th, a, d, t, temp, SD)
}

